chromanode:
  network: testnet # livenet | testnet

logger:
  level: verbose # verbose, info, warning, error
  filename: master.log

postgresql:
  url: postgres://user:pass@host:port/database_name

bitcoind:
  peer:
    host: localhost
    port: 18333
  rpc:
    host: localhost
    port: 18332
    user: bitcoinrpc
    pass: uMXXbdR2D7gh8BDofJC47dB6WyBEa8sRmM1N4JyPHv6
    protocol: http
